# Generated by Django 4.0.5 on 2022-06-25 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_judge', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='problemId',
        ),
        migrations.RemoveField(
            model_name='testcases',
            name='problemId',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Problem',
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
        migrations.DeleteModel(
            name='TestCases',
        ),
    ]
