# Generated by Django 4.0.5 on 2022-06-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('online_judge', '0002_remove_submission_problemid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('problemId', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
                ('difficulty', models.CharField(max_length=10)),
                ('solved', models.BooleanField(default=False)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
    ]
