# Generated by Django 4.0.5 on 2022-06-25 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_judge', '0006_problem_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='problemId',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='problemId',
        ),
        migrations.DeleteModel(
            name='Problem',
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
        migrations.DeleteModel(
            name='Testcase',
        ),
    ]
